using System.IO;
using Microsoft.CodeAnalysis;

namespace SourceGenerator;

[Generator]
internal class FluentAPIGenerator : ISourceGenerator
{
	public void Initialize(GeneratorInitializationContext context)
	{
		// context.RegisterForSyntaxNotifications();
	}

	public void Execute(GeneratorExecutionContext context)
	{
		context.AddSource("MyClass.g.cs", $@"// <auto-generated/>
#nullable enable
public class MyClass
{{
	public const string MyConstant = ""Hello from {nameof(FluentAPIGenerator)}"";
}}
");
	}
}